### ISSUE TITLE
Latex table label 

### ISSUE THREAD

**Issue by zhuwang46** [gorkang/html2latex#10]
A latex file temp.tex can be generated as follows. However, the file doesn't have label, which should be quite useful in a latex file.
 
'''
library(html2latex)
  library(lme4)
  library(sjPlot)
  
  # This is a terrible model
  model = lmer(mpg ~ cyl * disp + (1|vs), mtcars)
  
  # We save the sjPlot table to an .html file
  
  TAB = sjPlot::tab_model(
    model,
    show.r2 = TRUE,
    show.icc = FALSE,
    show.re.var = FALSE,
    p.style = "scientific",
    emph.p = TRUE,
    file = "temp.html")
html2pdf(filename = "temp.html", 
  table_width = 13, 
   silent = TRUE, 
   style = TRUE, 
   build_pdf = TRUE, 
   clean = TRUE)
'''

**Comment by gorkang** [comment]
You can manually add the label. See attached example. I added \label{table1} before the \end{longtable} line without issues. 

[temp-file.zip](https://github.com/gorkang/html2latex/files/9356974/temp-file.zip)

**Comment by zhuwang46** [comment]
The table can be cited but the issue is the text doesn't indicate Table 1. If there is only one table, no issue. What about two or multiple tables in a file?

**Comment by gorkang** [comment]
Please see the attached files in [temp-file.zip](https://github.com/gorkang/html2latex/files/9356974/temp-file.zip). The text in the rendered pdf inside the zip does indicate "Table 1". You just need to add \label{table1} before the \end{longtable} line. There is a .tex file in the zip where you can see for yourself.

If you want to send a Pull Request fixing this issue, I would be very happy to review it.

**Comment by gorkang** [comment]
I added the functionality in the last version of the package. 

Install with: remotes::install_github("gorkang/html2latex")

You can now use the name_table parameter:

html2pdf(filename = "temp.html", table_width = 13, silent = FALSE,
         style = TRUE, build_pdf = TRUE, clean = TRUE, name_table = "TABLEX")
