### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by AtienoRasanga** [gorkang/html2latex#11]
Hi, 

I get the error below trying to convert my model.

![Snip20220820_1](https://user-images.githubusercontent.com/2157239/185759263-e916398b-13db-4b9c-81fa-48615cf50bd8.png)

How can I resolve this?

**Comment by gorkang** [comment]
Could you share a [reproducible](https://reprex.tidyverse.org/) example? Thanks!

PD: Remember to set silent = FALSE to be able to see more feedback in the console.

**Comment by gorkang** [comment]
Please, reinstall the package ( `remotes::install_github("gorkang/html2latex")` ) and try again. 

I changed the pdf rendering function to something that should be more robust.

Let me know how it goes.
