### ISSUE TITLE
TAB =  sjPlot::tab_model doesn't generate html

### ISSUE THREAD

**Issue by andreifoldes** [gorkang/html2latex#14]
From the tutorial on Windows
TAB = sjPlot::tab_model(
    model,
    show.r2 = TRUE,
    show.icc = FALSE,
    show.re.var = FALSE,
    p.style = "scientific",
    emph.p = TRUE,
    file = "temp.html") doesnt generate the html, only when its not assigned.

Is that on purpose?

**Comment by gorkang** [comment]
Thanks for reporting it. Fixed now.
