### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by LuiNov** [gorkang/html2latex#7]
Hey, 
I tried out your function but it doesnt't work. Am I doing something wrong? Heres what I go
![Bildschirmfoto 2021-10-22 um 08 47 05](https://user-images.githubusercontent.com/84698983/138406229-63a47950-4bb0-4225-90d6-f8c5904bd399.png)
t

**Comment by gorkang** [comment]
Sorry I have no MacOS available to debug, but it seems you have 2 issues:

- Is Libreoffice installed, and if so, in the folder given in the message?
- No Java Runtime  installed?
