### ISSUE TITLE
How to add label in a generated latex file?

### ISSUE THREAD

**Issue by zhuwang46** [gorkang/html2latex#9]
# Load html2pdf.R function
source("R/html2pdf.R")
    
# Create tex and pdf
html2pdf(filename = "temp.html", page_width = 13, build_pdf = TRUE, silent = TRUE)

It seems a table label doesn't work after manually adding \label in temp.tex.

**Comment by gorkang** [comment]
This system is definitely not ready to handle manual manipulations of the tex intermediate files. In any case, it seems you have a latex issue. In any case, without a fully reproducible example, there isn't much I can do to help.
